name: Gating

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}

jobs:
  build-image-integration-tests:
    name: Build Cachi2 image and run integration tests on it
    runs-on: ubuntu-24.04

    steps:
      # - name: Install required packages
      #   run: |
      #     ls -l /usr/bin/

      - name: Different python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: ASDF
        run: python3 --version
